package edu.brown.cs.student.TestCreators;

import java.util.Objects;

/** Class representing an animal object – for testing */
public class Animal {

  private String name;
  private Integer age;
  private String species;
  private Integer numTag;

  /**
   * Constructor for an Animal object
   *
   * @param name name of the animal
   * @param age age of the animal (Integer)
   * @param species species of the animal
   * @param numTag ID number of the animal (Integer)
   */
  public Animal(String name, Integer age, String species, Integer numTag) {
    this.name = name;
    this.age = age;
    this.species = species;
    this.numTag = numTag;
  }

  /**
   * Overridden equals method for Animals Generated by IntelliJ as demonstrated in lecture
   *
   * @param o Object to be compared for equality
   * @return Boolean indicating whether the two objects are equal
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || this.getClass() != o.getClass()) {
      return false;
    }
    Animal animal = (Animal) o;
    return Objects.equals(this.name, animal.name)
        && Objects.equals(this.age, animal.age)
        && Objects.equals(this.species, animal.species)
        && Objects.equals(this.numTag, animal.numTag);
  }

  /**
   * Overridden hashCode method for Animals Generated by IntelliJ as demonstrated in lecture
   *
   * @return int to be used for hashing the Animal object
   */
  @Override
  public int hashCode() {
    return Objects.hash(this.name, this.age, this.species, this.numTag);
  }
}
