package edu.brown.cs.student.TestCreators;

import java.util.Objects;

/** Class to represent Dance objects (for testing) */
public class Dance {

  private String style;
  private String vibe;
  private Boolean shoes;

  /**
   * Constructor for a Dance object
   *
   * @param style the style of the dance
   * @param vibe the vibes of the dance style
   * @param shoes Boolean representing whether dancers of this style typically wear shoes
   */
  public Dance(String style, String vibe, Boolean shoes) {
    this.style = style;
    this.vibe = vibe;
    this.shoes = shoes;
  }

  /**
   * Overridden equals method for Dances Generated by IntelliJ as demonstrated in lecture
   *
   * @param o Object to be compared for equality
   * @return Boolean indicating whether the two objects are equal
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || this.getClass() != o.getClass()) {
      return false;
    }
    Dance dance = (Dance) o;
    return Objects.equals(this.style, dance.style)
        && Objects.equals(this.vibe, dance.vibe)
        && Objects.equals(this.shoes, dance.shoes);
  }

  /**
   * Overridden hashCode method for Dances Generated by IntelliJ as demonstrated in lecture
   *
   * @return int to be used for hashing the Dance object
   */
  @Override
  public int hashCode() {
    return Objects.hash(this.style, this.vibe, this.shoes);
  }
}
